### ISSUE TITLE
Generic css class names conflict

### ISSUE THREAD

**Issue by itainoam** [w11k/w11k-select#36]
* **I'm submitting a ...**
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

Many of the css classes in the default template have a very generic name. They conflict with the app styling and sometimes the select is styled with the app's css. For example "header" could be "w11k-header" to prevent that problem.

**Comment by pburgmer** [comment]
Hi,

Thanks for using w11k-select and your feedback.

The CSS selectors are all prefixed with the class w11k-select (```.w11k-select .header```). I thought this should be enough, but apparently it's not.

We have to discuss this change because it will be a breaking change for all users depending on our class names and structures. @CanKattwinkel What do you think about it?

A selector .selected for the hole application without any context isn't best practise too. Maybe you can use less generic selectors ;)

**Comment by CanKattwinkel** [comment]
I looked into the issue and I indeed found a class that was not prefixed (fixed with 0.10.3 https://github.com/w11k/w11k-select/commit/7ea24994e16a37c3ecc7aa2ae457491c2b3b973c).

But in general i totally agree with you @pburgmer. `.w11k-select .header` is enough scoping. If you use generic css class names in your styles there are easier ways to prevent propagation of the styles. E.g. use `body > .header` in your custom css.
